from pathlib import Path

from src.detection.realtime_detector import start_realtime_detection
from src.monitoring.alert_monitor import (
    load_alerts,
    calculate_statistics,
    display_statistics
)


MODEL_FILE = Path("models/random_forest_model.pkl")
ALERT_LOG = Path("logs/alerts.log")


def verify_environment():
    """Verify required IDS resources are available."""

    print("=" * 60)
    print("AI-Based Network Intrusion Detection System")
    print("Phase 7: End-to-End IDS Integration")
    print("=" * 60)

    print("\nChecking required resources...")

    if not MODEL_FILE.exists():
        raise FileNotFoundError(
            f"ML model not found: {MODEL_FILE}"
        )

    print(f"[OK] ML model found: {MODEL_FILE}")

    if not ALERT_LOG.parent.exists():
        ALERT_LOG.parent.mkdir(
            parents=True,
            exist_ok=True
        )

    print(f"[OK] Alert directory available: {ALERT_LOG.parent}")

    print("\nEnvironment verification completed.")


def run_detection(
    interface="eth0",
    packet_limit=10
):
    """Run the Phase 5 real-time detection engine."""

    print("\n" + "=" * 60)
    print("Starting Real-Time Detection")
    print("=" * 60)

    start_realtime_detection(
        interface=interface,
        packet_limit=packet_limit
    )


def run_monitoring():
    """Analyze alerts generated by the detection engine."""

    print("\n" + "=" * 60)
    print("Starting Alert Monitoring")
    print("=" * 60)

    if not ALERT_LOG.exists():
        print("No alert log found.")
        print("No suspicious traffic was recorded.")
        return

    alerts = load_alerts()

    statistics = calculate_statistics(alerts)

    display_statistics(statistics)


def run_ids(
    interface="eth0",
    packet_limit=10
):
    """Run the complete IDS workflow."""

    verify_environment()

    run_detection(
        interface=interface,
        packet_limit=packet_limit
    )

    run_monitoring()

    print("\n" + "=" * 60)
    print("Phase 7 End-to-End IDS Run Completed")
    print("=" * 60)


if __name__ == "__main__":
    run_ids(
        interface="eth0",
        packet_limit=10
    )
